# Generated by Django 3.1.3 on 2020-12-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
