# Generated by Django 3.1.3 on 2020-12-19 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201219_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
