# Generated by Django 3.1.3 on 2020-12-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='buyer',
        ),
        migrations.AddField(
            model_name='bid',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='auctions.user'),
            preserve_default=False,
        ),
    ]
