# Generated by Django 3.1.3 on 2020-12-05 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
